name: docker-demo-production

services:
  mongo:
    image: mongo:7.0.12
    volumes:
      - mongo_data:/data/db
    networks:
      - docker-demo-production

  api:
    build:
      context: ./backend
      target: production
    restart: unless-stopped
    env_file: ./backend/.env
    networks:
      - docker-demo-production
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      target: production
      args:
        VITE_API_URL: https://api.${DOMAIN_NAME}
    restart: unless-stopped
    networks:
      - docker-demo-production
    depends_on:
      - api

  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - docker-demo-production
    depends_on:
      - api
      - frontend

volumes:
  mongo_data:
  caddy_data:
  caddy_config:
networks:
  docker-demo-production:
    driver: bridge
